CREATE DATABASE db1_master;
CREATE DATABASE db1_slave1;
CREATE DATABASE db1_slave2;

CREATE DATABASE db2_master;
CREATE DATABASE db2_slave1;
CREATE DATABASE db2_slave2;

CREATE DATABASE db3_master;
CREATE DATABASE db3_slave1;
CREATE DATABASE db3_slave2;

CREATE USER 'readonly'@'%' IDENTIFIED BY "123";
GRANT SELECT ON *.* TO 'readonly'@'%';

USE db1_master;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db1_slave1;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db1_slave2;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_master;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_slave1;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db2_slave2;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_master;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_slave1;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

USE db3_slave2;
DROP TABLE IF EXISTS `user0`;
CREATE TABLE `user0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user1`;
CREATE TABLE `user1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order0`;
CREATE TABLE `order0` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order1`;
CREATE TABLE `order1` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cust`;
CREATE TABLE `cust` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart0`;
CREATE TABLE `depart0` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `depart1`;
CREATE TABLE `depart1` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;