USE db1_master;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db1_slave1;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db1_slave2;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db2_master;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db2_slave1;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db2_slave2;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db3_master;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db3_slave1;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;

USE db3_slave2;
TRUNCATE TABLE user0;
TRUNCATE TABLE user1;
TRUNCATE TABLE order0;
TRUNCATE TABLE order1;
TRUNCATE TABLE cust;
TRUNCATE TABLE depart0;
TRUNCATE TABLE depart1;