--DB1_MASTER
CREATE TABLESPACE DB1_MASTER DATAFILE 'DB1_MASTER.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER ROOT1 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB1_MASTER TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO ROOT1;
GRANT RESOURCE TO ROOT1;

CREATE TABLE "ROOT1"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "ROOT1"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT DBA TO ROOT1;

--DB1_SLAVE1
CREATE TABLESPACE DB1_SLAVE1 DATAFILE 'DB1_SLAVE1.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE11 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB1_SLAVE1 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE11;
GRANT RESOURCE TO SLAVE11;

CREATE TABLE "SLAVE11"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE11"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE11"."USER0" TO SLAVE11;
GRANT SELECT ON "SLAVE11"."USER1" TO SLAVE11;

--DB1_SLAVE2
CREATE TABLESPACE DB1_SLAVE2 DATAFILE 'DB1_SLAVE2.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE12 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB1_SLAVE2 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE12;
GRANT RESOURCE TO SLAVE12;

CREATE TABLE "SLAVE12"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE12"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE12"."USER0" TO SLAVE12;
GRANT SELECT ON "SLAVE12"."USER1" TO SLAVE12;

--DB2_MASTER
CREATE TABLESPACE DB2_MASTER DATAFILE 'DB2_MASTER.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER ROOT2 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB2_MASTER TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO ROOT2;
GRANT RESOURCE TO ROOT2;

CREATE TABLE "ROOT2"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "ROOT2"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT DBA TO ROOT2;

--DB2_SLAVE1
CREATE TABLESPACE DB2_SLAVE1 DATAFILE 'DB2_SLAVE1.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE21 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB2_SLAVE1 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE21;
GRANT RESOURCE TO SLAVE21;

CREATE TABLE "SLAVE21"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE21"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE21"."USER0" TO SLAVE21;
GRANT SELECT ON "SLAVE21"."USER1" TO SLAVE21;

--DB2_SLAVE2
CREATE TABLESPACE DB2_SLAVE2 DATAFILE 'DB2_SLAVE2.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE22 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB2_SLAVE2 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE22;
GRANT RESOURCE TO SLAVE22;

CREATE TABLE "SLAVE22"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE22"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE22"."USER0" TO SLAVE22;
GRANT SELECT ON "SLAVE22"."USER1" TO SLAVE22;

--DB3_MASTER
CREATE TABLESPACE DB3_MASTER DATAFILE 'DB3_MASTER.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER ROOT3 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB3_MASTER TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO ROOT3;
GRANT RESOURCE TO ROOT3;

CREATE TABLE "ROOT3"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "ROOT3"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT DBA TO ROOT3;

--DB3_SLAVE1
CREATE TABLESPACE DB3_SLAVE1 DATAFILE 'DB3_SLAVE1.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE31 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB3_SLAVE1 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE31;
GRANT RESOURCE TO SLAVE31;

CREATE TABLE "SLAVE31"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE31"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE31"."USER0" TO SLAVE31;
GRANT SELECT ON "SLAVE31"."USER1" TO SLAVE31;

--DB3_SLAVE2
CREATE TABLESPACE DB3_SLAVE2 DATAFILE 'DB3_SLAVE2.DAT' SIZE 10M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED; 
CREATE USER SLAVE32 PROFILE DEFAULT IDENTIFIED BY "123" DEFAULT TABLESPACE DB3_SLAVE2 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO SLAVE32;
GRANT RESOURCE TO SLAVE32;

CREATE TABLE "SLAVE32"."USER0" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "SLAVE32"."USER1" (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

GRANT SELECT ON "SLAVE32"."USER0" TO SLAVE32;
GRANT SELECT ON "SLAVE32"."USER1" TO SLAVE32;

