TRUNCATE TABLE "ROOT1"."USER0";
TRUNCATE TABLE "ROOT1"."USER1";
TRUNCATE TABLE "ROOT1"."ORDER0";
TRUNCATE TABLE "ROOT1"."ORDER1";
TRUNCATE TABLE "ROOT1"."CUST";
TRUNCATE TABLE "ROOT1"."DEPART0";
TRUNCATE TABLE "ROOT1"."DEPART1";

TRUNCATE TABLE "SLAVE11"."USER0";
TRUNCATE TABLE "SLAVE11"."USER1";
TRUNCATE TABLE "SLAVE11"."ORDER0";
TRUNCATE TABLE "SLAVE11"."ORDER1";
TRUNCATE TABLE "SLAVE11"."CUST";
TRUNCATE TABLE "SLAVE11"."DEPART0";
TRUNCATE TABLE "SLAVE11"."DEPART1";

TRUNCATE TABLE "SLAVE12"."USER0";
TRUNCATE TABLE "SLAVE12"."USER1";
TRUNCATE TABLE "SLAVE12"."ORDER0";
TRUNCATE TABLE "SLAVE12"."ORDER1";
TRUNCATE TABLE "SLAVE12"."CUST";
TRUNCATE TABLE "SLAVE12"."DEPART0";
TRUNCATE TABLE "SLAVE12"."DEPART1";

TRUNCATE TABLE "ROOT2"."USER0";
TRUNCATE TABLE "ROOT2"."USER1";
TRUNCATE TABLE "ROOT2"."ORDER0";
TRUNCATE TABLE "ROOT2"."ORDER1";
TRUNCATE TABLE "ROOT2"."CUST";
TRUNCATE TABLE "ROOT2"."DEPART0";
TRUNCATE TABLE "ROOT2"."DEPART1";

TRUNCATE TABLE "SLAVE21"."USER0";
TRUNCATE TABLE "SLAVE21"."USER1";
TRUNCATE TABLE "SLAVE21"."ORDER0";
TRUNCATE TABLE "SLAVE21"."ORDER1";
TRUNCATE TABLE "SLAVE21"."CUST";
TRUNCATE TABLE "SLAVE21"."DEPART0";
TRUNCATE TABLE "SLAVE21"."DEPART1";

TRUNCATE TABLE "SLAVE22"."USER0";
TRUNCATE TABLE "SLAVE22"."USER1";
TRUNCATE TABLE "SLAVE22"."ORDER0";
TRUNCATE TABLE "SLAVE22"."ORDER1";
TRUNCATE TABLE "SLAVE22"."CUST";
TRUNCATE TABLE "SLAVE22"."DEPART0";
TRUNCATE TABLE "SLAVE22"."DEPART1";

TRUNCATE TABLE "ROOT3"."USER0";
TRUNCATE TABLE "ROOT3"."USER1";
TRUNCATE TABLE "ROOT3"."ORDER0";
TRUNCATE TABLE "ROOT3"."ORDER1";
TRUNCATE TABLE "ROOT3"."CUST";
TRUNCATE TABLE "ROOT3"."DEPART0";
TRUNCATE TABLE "ROOT3"."DEPART1";

TRUNCATE TABLE "SLAVE31"."USER0";
TRUNCATE TABLE "SLAVE31"."USER1";
TRUNCATE TABLE "SLAVE31"."ORDER0";
TRUNCATE TABLE "SLAVE31"."ORDER1";
TRUNCATE TABLE "SLAVE31"."CUST";
TRUNCATE TABLE "SLAVE31"."DEPART0";
TRUNCATE TABLE "SLAVE31"."DEPART1";

TRUNCATE TABLE "SLAVE32"."USER0";
TRUNCATE TABLE "SLAVE32"."USER1";
TRUNCATE TABLE "SLAVE32"."ORDER0";
TRUNCATE TABLE "SLAVE32"."ORDER1";
TRUNCATE TABLE "SLAVE32"."CUST";
TRUNCATE TABLE "SLAVE32"."DEPART0";
TRUNCATE TABLE "SLAVE32"."DEPART1";