--DB1_MASTER
DROP USER ROOT1 CASCADE;
DROP TABLESPACE DB1_MASTER INCLUDING CONTENTS AND DATAFILES; 

--DB1_SLAVE1
DROP USER SLAVE11 CASCADE;
DROP TABLESPACE DB1_SLAVE1 INCLUDING CONTENTS AND DATAFILES; 

--DB1_SLAVE2
DROP USER SLAVE12 CASCADE;
DROP TABLESPACE DB1_SLAVE2 INCLUDING CONTENTS AND DATAFILES; 

--DB2_MASTER
DROP USER ROOT2 CASCADE;
DROP TABLESPACE DB2_MASTER INCLUDING CONTENTS AND DATAFILES; 

--DB2_SLAVE1
DROP USER SLAVE21 CASCADE;
DROP TABLESPACE DB2_SLAVE1 INCLUDING CONTENTS AND DATAFILES; 

--DB2_SLAVE2
DROP USER SLAVE22 CASCADE;
DROP TABLESPACE DB2_SLAVE2 INCLUDING CONTENTS AND DATAFILES; 

--DB3_MASTER
DROP USER ROOT3 CASCADE;
DROP TABLESPACE DB3_MASTER INCLUDING CONTENTS AND DATAFILES; 

--DB3_SLAVE1
DROP USER SLAVE31 CASCADE;
DROP TABLESPACE DB3_SLAVE1 INCLUDING CONTENTS AND DATAFILES; 

--DB3_SLAVE2
DROP USER SLAVE32 CASCADE;
DROP TABLESPACE DB3_SLAVE2 INCLUDING CONTENTS AND DATAFILES; 



